export const mockDeviceData = [
  {
    id: 1,
    name: "asphalt sensor - Ardabil Airport",
    uuid: "9b7e21d4-4c2a-4f6a-91a1-ardabil001",

    location: {
      address: "Ardabil Airport (OITL), Ardabil, Ardabil Province, Iran",
      latitude: 38.32639,
      longitude: 48.42444,
    },

    status: "online",

    energy: {
      storage: {
        type: "battery",
        capacity_wh: 100000, // 100 kWh
        current_level_percent: 81,
      },
      generation: [
        {
          type: "solar",
          max_power_w: 150,
          efficiency_percent: 19,
        },
        {
          type: "geothermal",
          max_power_w: 50,
        },
      ],
    },

    energy_summary: {
      total_consumed_kwh: 80,
      total_generated_kwh: 12,
      net_consumed_kwh: 68,
    },

    heating_status_daily: [
      { hour: 0, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 1, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 2, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 3, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 4, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 5, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 6, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 7, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 8, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 9, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 10, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 11, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 12, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 13, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 14, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 15, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 16, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 17, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 18, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 19, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 20, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 21, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 22, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 23, status: "ON", source: "solar", energy_consumed_kwh: 5 },
    ],

    solar_metrics: {
      source: "pv_atlas",
      period: "daily",
      units: "kWh/m²",
      irradiation: {
        dni: 1695.7,
        ghi: 1363.5,
        dhi: 508.9,
        gti_opt: 1760,
      },
      optimal_panel_position: {
        tilt_deg: 45,
        azimuth_deg: 180,
      },
      environmental_context: {
        avg_air_temperature_c: 3,
        elevation_m: 562,
      },
    },

    sun_angle_daily: [
      { hour: 0, angle_deg: 0 },
      { hour: 1, angle_deg: 0 },
      { hour: 2, angle_deg: 0 },
      { hour: 3, angle_deg: 0 },
      { hour: 4, angle_deg: 0 },
      { hour: 5, angle_deg: 0 },
      { hour: 6, angle_deg: 0 },
      { hour: 7, angle_deg: 3 },
      { hour: 8, angle_deg: 10 },
      { hour: 9, angle_deg: 18 },
      { hour: 10, angle_deg: 26 },
      { hour: 11, angle_deg: 32 },
      { hour: 12, angle_deg: 36 },
      { hour: 13, angle_deg: 35 },
      { hour: 14, angle_deg: 30 },
      { hour: 15, angle_deg: 22 },
      { hour: 16, angle_deg: 14 },
      { hour: 17, angle_deg: 6 },
      { hour: 18, angle_deg: 0 },
      { hour: 19, angle_deg: 0 },
      { hour: 20, angle_deg: 0 },
      { hour: 21, angle_deg: 0 },
      { hour: 22, angle_deg: 0 },
      { hour: 23, angle_deg: 0 },
    ],

    temperature_records: {
      air_temperature: [
        { hour: 0, value_c: -11.8 },
        { hour: 1, value_c: -12.2 },
        { hour: 2, value_c: -12.6 },
        { hour: 3, value_c: -13.1 },
        { hour: 4, value_c: -13.5 },
        { hour: 5, value_c: -13.0 },
        { hour: 6, value_c: -12.2 },
        { hour: 7, value_c: -10.8 },
        { hour: 8, value_c: -8.9 },
        { hour: 9, value_c: -6.7 },
        { hour: 10, value_c: -4.5 },
        { hour: 11, value_c: -2.9 },
        { hour: 12, value_c: -1.6 },
        { hour: 13, value_c: -1.2 },
        { hour: 14, value_c: -2.0 },
        { hour: 15, value_c: -3.6 },
        { hour: 16, value_c: -5.5 },
        { hour: 17, value_c: -7.3 },
        { hour: 18, value_c: -8.9 },
        { hour: 19, value_c: -10.1 },
        { hour: 20, value_c: -10.9 },
        { hour: 21, value_c: -11.4 },
        { hour: 22, value_c: -11.9 },
        { hour: 23, value_c: -12.3 },
      ],
      asphalt_temperature: [
        { hour: 0, value_c: -10.5 },
        { hour: 1, value_c: -11.0 },
        { hour: 2, value_c: -11.5 },
        { hour: 3, value_c: -12.0 },
        { hour: 4, value_c: -12.4 },
        { hour: 5, value_c: -12.0 },
        { hour: 6, value_c: -11.5 },
        { hour: 7, value_c: -10.2 },
        { hour: 8, value_c: -8.5 },
        { hour: 9, value_c: -6.2 },
        { hour: 10, value_c: -4.0 },
        { hour: 11, value_c: -2.5 },
        { hour: 12, value_c: -1.5 },
        { hour: 13, value_c: -1.2 },
        { hour: 14, value_c: -1.8 },
        { hour: 15, value_c: -3.0 },
        { hour: 16, value_c: -5.0 },
        { hour: 17, value_c: -6.8 },
        { hour: 18, value_c: -8.5 },
        { hour: 19, value_c: -9.8 },
        { hour: 20, value_c: -10.6 },
        { hour: 21, value_c: -11.2 },
        { hour: 22, value_c: -11.7 },
        { hour: 23, value_c: -12.2 },
      ],
    },

    icing_probability_daily: [
      { hour: 0, probability: 0.96 },
      { hour: 1, probability: 0.97 },
      { hour: 2, probability: 0.98 },
      { hour: 3, probability: 0.99 },
      { hour: 4, probability: 0.99 },
      { hour: 5, probability: 0.98 },
      { hour: 6, probability: 0.96 },
      { hour: 7, probability: 0.92 },
      { hour: 8, probability: 0.85 },
      { hour: 9, probability: 0.68 },
      { hour: 10, probability: 0.48 },
      { hour: 11, probability: 0.32 },
      { hour: 12, probability: 0.25 },
      { hour: 13, probability: 0.24 },
      { hour: 14, probability: 0.3 },
      { hour: 15, probability: 0.5 },
      { hour: 16, probability: 0.7 },
      { hour: 17, probability: 0.83 },
      { hour: 18, probability: 0.91 },
      { hour: 19, probability: 0.95 },
      { hour: 20, probability: 0.97 },
      { hour: 21, probability: 0.98 },
      { hour: 22, probability: 0.99 },
      { hour: 23, probability: 0.99 },
    ],

    notifications_daily: [
      {
        hour: 0,
        message: "High icing probability detected (96%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 1,
        message: "High icing probability detected (97%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 2,
        message: "High icing probability detected (98%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 3,
        message: "High icing probability detected (99%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 4,
        message: "High icing probability detected (99%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 5,
        message: "High icing probability detected (98%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 6,
        message: "High icing probability detected (96%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 7,
        message: "Heater turned OFF. Icing probability decreased to 92%.",
        type: "info",
      },
      {
        hour: 8,
        message: "Heater remains OFF. Icing probability 85%.",
        type: "info",
      },
      {
        hour: 9,
        message: "Heater remains OFF. Icing probability 68%.",
        type: "info",
      },
      {
        hour: 10,
        message: "Heater remains OFF. Icing probability 48%.",
        type: "info",
      },
      {
        hour: 11,
        message: "Heater remains OFF. Icing probability 32%.",
        type: "info",
      },
      {
        hour: 12,
        message: "Heater remains OFF. Icing probability 25%.",
        type: "info",
      },
      {
        hour: 13,
        message: "Heater remains OFF. Icing probability 24%.",
        type: "info",
      },
      {
        hour: 14,
        message: "Heater remains OFF. Icing probability 30%.",
        type: "info",
      },
      {
        hour: 15,
        message: "Heater turned ON. Icing probability increased to 50%.",
        type: "info",
      },
      { hour: 16, message: "Heater ON. Icing probability 70%.", type: "info" },
      { hour: 17, message: "Heater ON. Icing probability 83%.", type: "info" },
      {
        hour: 18,
        message: "Heater ON. Icing probability 91%.",
        type: "warning",
      },
      {
        hour: 19,
        message: "Heater ON. Icing probability 95%.",
        type: "warning",
      },
      {
        hour: 20,
        message: "Heater ON. Icing probability 97%.",
        type: "warning",
      },
      {
        hour: 21,
        message: "Heater ON. Icing probability 98%.",
        type: "warning",
      },
      {
        hour: 22,
        message: "Heater ON. Icing probability 99%.",
        type: "warning",
      },
      {
        hour: 23,
        message: "Heater ON. Icing probability 99%.",
        type: "warning",
      },
    ],

    first_data_timestamp: "2025-01-15T00:00:00Z",
    last_data_timestamp: "2025-01-15T23:59:59Z",
  },
];
