export const mockDeviceData = [
  {
    id: 1,
    name: "asphalt sensor - Ardabil Airport",
    uuid: "9b7e21d4-4c2a-4f6a-91a1-ardabil001",

    location: {
      address: "Ardabil Airport (OITL), Ardabil, Ardabil Province, Iran",
      latitude: 38.32639,
      longitude: 48.42444,
    },

    status: "online",

    energy: {
      storage: {
        type: "battery",
        capacity_wh: 100000, // 100 kWh
        current_level_percent: 81,
      },
      generation: [
        {
          type: "solar",
          max_power_w: 150,
          efficiency_percent: 19,
        },
        {
          type: "geothermal",
          max_power_w: 50,
        },
      ],
    },

    energy_summary: {
      total_consumed_kwh: 80,
      total_generated_kwh: 12,
      net_consumed_kwh: 68,
    },

    heating_status_daily: [
      { hour: 0, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 1, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 2, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 3, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 4, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 5, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 6, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 7, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 8, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 9, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 10, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 11, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 12, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 13, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 14, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 15, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 16, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 17, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 18, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 19, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 20, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 21, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 22, status: "ON", source: "solar", energy_consumed_kwh: 5 },
      { hour: 23, status: "ON", source: "solar", energy_consumed_kwh: 5 },
    ],

    solar_metrics: {
      source: "pv_atlas",
      period: "daily",
      units: "kWh/m²",
      irradiation: {
        dni: 1695.7,
        ghi: 1363.5,
        dhi: 508.9,
        gti_opt: 1760,
      },
      optimal_panel_position: {
        tilt_deg: 45,
        azimuth_deg: 180,
      },
      environmental_context: {
        avg_air_temperature_c: 3,
        elevation_m: 562,
      },
    },

    sun_angle_daily: [
      { hour: 0, angle_deg: 0 },
      { hour: 1, angle_deg: 0 },
      { hour: 2, angle_deg: 0 },
      { hour: 3, angle_deg: 0 },
      { hour: 4, angle_deg: 0 },
      { hour: 5, angle_deg: 0 },
      { hour: 6, angle_deg: 0 },
      { hour: 7, angle_deg: 3 },
      { hour: 8, angle_deg: 10 },
      { hour: 9, angle_deg: 18 },
      { hour: 10, angle_deg: 26 },
      { hour: 11, angle_deg: 32 },
      { hour: 12, angle_deg: 36 },
      { hour: 13, angle_deg: 35 },
      { hour: 14, angle_deg: 30 },
      { hour: 15, angle_deg: 22 },
      { hour: 16, angle_deg: 14 },
      { hour: 17, angle_deg: 6 },
      { hour: 18, angle_deg: 0 },
      { hour: 19, angle_deg: 0 },
      { hour: 20, angle_deg: 0 },
      { hour: 21, angle_deg: 0 },
      { hour: 22, angle_deg: 0 },
      { hour: 23, angle_deg: 0 },
    ],

    temperature_records: {
      air_temperature: [
        { hour: 0, value_c: -11.8 },
        { hour: 1, value_c: -12.2 },
        { hour: 2, value_c: -12.6 },
        { hour: 3, value_c: -13.1 },
        { hour: 4, value_c: -13.5 },
        { hour: 5, value_c: -13.0 },
        { hour: 6, value_c: -12.2 },
        { hour: 7, value_c: -10.8 },
        { hour: 8, value_c: -8.9 },
        { hour: 9, value_c: -6.7 },
        { hour: 10, value_c: -4.5 },
        { hour: 11, value_c: -2.9 },
        { hour: 12, value_c: -1.6 },
        { hour: 13, value_c: -1.2 },
        { hour: 14, value_c: -2.0 },
        { hour: 15, value_c: -3.6 },
        { hour: 16, value_c: -5.5 },
        { hour: 17, value_c: -7.3 },
        { hour: 18, value_c: -8.9 },
        { hour: 19, value_c: -10.1 },
        { hour: 20, value_c: -10.9 },
        { hour: 21, value_c: -11.4 },
        { hour: 22, value_c: -11.9 },
        { hour: 23, value_c: -12.3 },
      ],
      asphalt_temperature: [
        { hour: 0, value_c: -10.5 },
        { hour: 1, value_c: -11.0 },
        { hour: 2, value_c: -11.5 },
        { hour: 3, value_c: -12.0 },
        { hour: 4, value_c: -12.4 },
        { hour: 5, value_c: -12.0 },
        { hour: 6, value_c: -11.5 },
        { hour: 7, value_c: -10.2 },
        { hour: 8, value_c: -8.5 },
        { hour: 9, value_c: -6.2 },
        { hour: 10, value_c: -4.0 },
        { hour: 11, value_c: -2.5 },
        { hour: 12, value_c: -1.5 },
        { hour: 13, value_c: -1.2 },
        { hour: 14, value_c: -1.8 },
        { hour: 15, value_c: -3.0 },
        { hour: 16, value_c: -5.0 },
        { hour: 17, value_c: -6.8 },
        { hour: 18, value_c: -8.5 },
        { hour: 19, value_c: -9.8 },
        { hour: 20, value_c: -10.6 },
        { hour: 21, value_c: -11.2 },
        { hour: 22, value_c: -11.7 },
        { hour: 23, value_c: -12.2 },
      ],
    },

    icing_probability_daily: [
      { hour: 0, probability: 0.96 },
      { hour: 1, probability: 0.97 },
      { hour: 2, probability: 0.98 },
      { hour: 3, probability: 0.99 },
      { hour: 4, probability: 0.99 },
      { hour: 5, probability: 0.98 },
      { hour: 6, probability: 0.96 },
      { hour: 7, probability: 0.92 },
      { hour: 8, probability: 0.85 },
      { hour: 9, probability: 0.68 },
      { hour: 10, probability: 0.48 },
      { hour: 11, probability: 0.32 },
      { hour: 12, probability: 0.25 },
      { hour: 13, probability: 0.24 },
      { hour: 14, probability: 0.3 },
      { hour: 15, probability: 0.5 },
      { hour: 16, probability: 0.7 },
      { hour: 17, probability: 0.83 },
      { hour: 18, probability: 0.91 },
      { hour: 19, probability: 0.95 },
      { hour: 20, probability: 0.97 },
      { hour: 21, probability: 0.98 },
      { hour: 22, probability: 0.99 },
      { hour: 23, probability: 0.99 },
    ],

    notifications_daily: [
      {
        hour: 0,
        message: "High icing probability detected (96%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 1,
        message: "High icing probability detected (97%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 2,
        message: "High icing probability detected (98%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 3,
        message: "High icing probability detected (99%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 4,
        message: "High icing probability detected (99%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 5,
        message: "High icing probability detected (98%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 6,
        message: "High icing probability detected (96%). Heater is ON.",
        type: "warning",
      },
      {
        hour: 7,
        message: "Heater turned OFF. Icing probability decreased to 92%.",
        type: "info",
      },
      {
        hour: 8,
        message: "Heater remains OFF. Icing probability 85%.",
        type: "info",
      },
      {
        hour: 9,
        message: "Heater remains OFF. Icing probability 68%.",
        type: "info",
      },
      {
        hour: 10,
        message: "Heater remains OFF. Icing probability 48%.",
        type: "info",
      },
      {
        hour: 11,
        message: "Heater remains OFF. Icing probability 32%.",
        type: "info",
      },
      {
        hour: 12,
        message: "Heater remains OFF. Icing probability 25%.",
        type: "info",
      },
      {
        hour: 13,
        message: "Heater remains OFF. Icing probability 24%.",
        type: "info",
      },
      {
        hour: 14,
        message: "Heater remains OFF. Icing probability 30%.",
        type: "info",
      },
      {
        hour: 15,
        message: "Heater turned ON. Icing probability increased to 50%.",
        type: "info",
      },
      { hour: 16, message: "Heater ON. Icing probability 70%.", type: "info" },
      { hour: 17, message: "Heater ON. Icing probability 83%.", type: "info" },
      {
        hour: 18,
        message: "Heater ON. Icing probability 91%.",
        type: "warning",
      },
      {
        hour: 19,
        message: "Heater ON. Icing probability 95%.",
        type: "warning",
      },
      {
        hour: 20,
        message: "Heater ON. Icing probability 97%.",
        type: "warning",
      },
      {
        hour: 21,
        message: "Heater ON. Icing probability 98%.",
        type: "warning",
      },
      {
        hour: 22,
        message: "Heater ON. Icing probability 99%.",
        type: "warning",
      },
      {
        hour: 23,
        message: "Heater ON. Icing probability 99%.",
        type: "warning",
      },
    ],

    first_data_timestamp: "2025-01-15T00:00:00Z",
    last_data_timestamp: "2025-01-15T23:59:59Z",
  },
  {
    id: 2,
    name: "asphalt sensor - Hamedan Asadabad Pass",
    uuid: "3f2c91e1-6bda-4c7a-9f31-hamedan002",

    location: {
      address: "Asadabad Pass, Hamedan Province, Iran",
      latitude: 34.7821,
      longitude: 48.1186,
    },

    status: "online",

    energy: {
      storage: {
        type: "battery",
        capacity_wh: 150000, // 150 kWh
        current_level_percent: 72,
      },
      generation: [
        {
          type: "solar",
          max_power_w: 120,
          efficiency_percent: 17,
        },
        {
          type: "geothermal",
          max_power_w: 80,
        },
      ],
    },

    energy_summary: {
      total_consumed_kwh: 95,
      total_generated_kwh: 14,
      net_consumed_kwh: 81,
    },

    heating_status_daily: [
      { hour: 0, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 1, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 2, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 3, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 4, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 5, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 6, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 7, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 8, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 9, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 10, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 11, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 12, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 13, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 14, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 15, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 16, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 17, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 18, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 19, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 20, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 21, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 22, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 23, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
    ],

    solar_metrics: {
      source: "pv_atlas",
      period: "daily",
      units: "kWh/m²",
      irradiation: {
        dni: 1320,
        ghi: 1040,
        dhi: 410,
        gti_opt: 1400,
      },
      optimal_panel_position: {
        tilt_deg: 55,
        azimuth_deg: 180,
      },
      environmental_context: {
        avg_air_temperature_c: -3,
        elevation_m: 1850,
      },
    },

    sun_angle_daily: [
      { hour: 0, angle_deg: 0 },
      { hour: 1, angle_deg: 0 },
      { hour: 2, angle_deg: 0 },
      { hour: 3, angle_deg: 0 },
      { hour: 4, angle_deg: 0 },
      { hour: 5, angle_deg: 0 },
      { hour: 6, angle_deg: 1 },
      { hour: 7, angle_deg: 4 },
      { hour: 8, angle_deg: 11 },
      { hour: 9, angle_deg: 19 },
      { hour: 10, angle_deg: 27 },
      { hour: 11, angle_deg: 33 },
      { hour: 12, angle_deg: 36 },
      { hour: 13, angle_deg: 34 },
      { hour: 14, angle_deg: 29 },
      { hour: 15, angle_deg: 21 },
      { hour: 16, angle_deg: 13 },
      { hour: 17, angle_deg: 5 },
      { hour: 18, angle_deg: 0 },
      { hour: 19, angle_deg: 0 },
      { hour: 20, angle_deg: 0 },
      { hour: 21, angle_deg: 0 },
      { hour: 22, angle_deg: 0 },
      { hour: 23, angle_deg: 0 },
    ],

    temperature_records: {
      air_temperature: [
        { hour: 0, value_c: -17.2 },
        { hour: 1, value_c: -17.6 },
        { hour: 2, value_c: -18.0 },
        { hour: 3, value_c: -18.4 },
        { hour: 4, value_c: -18.7 },
        { hour: 5, value_c: -18.1 },
        { hour: 6, value_c: -17.2 },
        { hour: 7, value_c: -15.6 },
        { hour: 8, value_c: -13.2 },
        { hour: 9, value_c: -10.5 },
        { hour: 10, value_c: -8.1 },
        { hour: 11, value_c: -6.3 },
        { hour: 12, value_c: -5.2 },
        { hour: 13, value_c: -5.0 },
        { hour: 14, value_c: -5.8 },
        { hour: 15, value_c: -7.4 },
        { hour: 16, value_c: -9.6 },
        { hour: 17, value_c: -11.8 },
        { hour: 18, value_c: -13.9 },
        { hour: 19, value_c: -15.4 },
        { hour: 20, value_c: -16.2 },
        { hour: 21, value_c: -16.8 },
        { hour: 22, value_c: -17.3 },
        { hour: 23, value_c: -17.7 },
      ],
      asphalt_temperature: [
        { hour: 0, value_c: -13.5 },
        { hour: 1, value_c: -14.0 },
        { hour: 2, value_c: -14.6 },
        { hour: 3, value_c: -15.0 },
        { hour: 4, value_c: -15.4 },
        { hour: 5, value_c: -15.0 },
        { hour: 6, value_c: -14.4 },
        { hour: 7, value_c: -13.0 },
        { hour: 8, value_c: -11.2 },
        { hour: 9, value_c: -8.6 },
        { hour: 10, value_c: -6.3 },
        { hour: 11, value_c: -4.8 },
        { hour: 12, value_c: -3.9 },
        { hour: 13, value_c: -3.7 },
        { hour: 14, value_c: -4.4 },
        { hour: 15, value_c: -5.9 },
        { hour: 16, value_c: -7.8 },
        { hour: 17, value_c: -9.6 },
        { hour: 18, value_c: -11.4 },
        { hour: 19, value_c: -12.8 },
        { hour: 20, value_c: -13.6 },
        { hour: 21, value_c: -14.2 },
        { hour: 22, value_c: -14.7 },
        { hour: 23, value_c: -15.1 },
      ],
    },

    icing_probability_daily: [
      { hour: 0, probability: 0.99 },
      { hour: 1, probability: 0.99 },
      { hour: 2, probability: 0.99 },
      { hour: 3, probability: 1.0 },
      { hour: 4, probability: 1.0 },
      { hour: 5, probability: 0.99 },
      { hour: 6, probability: 0.98 },
      { hour: 7, probability: 0.95 },
      { hour: 8, probability: 0.88 },
      { hour: 9, probability: 0.72 },
      { hour: 10, probability: 0.55 },
      { hour: 11, probability: 0.4 },
      { hour: 12, probability: 0.35 },
      { hour: 13, probability: 0.34 },
      { hour: 14, probability: 0.42 },
      { hour: 15, probability: 0.6 },
      { hour: 16, probability: 0.78 },
      { hour: 17, probability: 0.9 },
      { hour: 18, probability: 0.96 },
      { hour: 19, probability: 0.98 },
      { hour: 20, probability: 0.99 },
      { hour: 21, probability: 0.99 },
      { hour: 22, probability: 1.0 },
      { hour: 23, probability: 1.0 },
    ],

    notifications_daily: [
      {
        hour: 0,
        message: "Extreme icing risk detected (99%). Heater ON.",
        type: "warning",
      },
      {
        hour: 1,
        message: "Extreme icing risk persists. Heater remains ON.",
        type: "warning",
      },
      {
        hour: 2,
        message: "Heater active due to sustained sub-zero asphalt temperature.",
        type: "warning",
      },
      {
        hour: 3,
        message: "Critical icing conditions detected.",
        type: "warning",
      },
      {
        hour: 4,
        message: "Critical icing conditions detected.",
        type: "warning",
      },
      {
        hour: 5,
        message: "Heater remains ON. Icing probability 99%.",
        type: "warning",
      },
      {
        hour: 6,
        message: "Heater remains ON. Icing probability 98%.",
        type: "warning",
      },
      {
        hour: 7,
        message:
          "Solar contribution detected. Heater partially supported by solar.",
        type: "info",
      },
      {
        hour: 8,
        message:
          "Heater turned OFF. Icing probability dropped below threshold.",
        type: "info",
      },
      {
        hour: 9,
        message: "Stable conditions. Heater remains OFF.",
        type: "info",
      },
      {
        hour: 10,
        message: "Stable conditions. Heater remains OFF.",
        type: "info",
      },
      {
        hour: 11,
        message: "Stable conditions. Heater remains OFF.",
        type: "info",
      },
      {
        hour: 12,
        message: "Lowest icing probability recorded today.",
        type: "info",
      },
      {
        hour: 13,
        message: "Lowest icing probability recorded today.",
        type: "info",
      },
      {
        hour: 14,
        message: "Icing probability starting to rise.",
        type: "info",
      },
      {
        hour: 15,
        message: "Heater reactivated due to rising icing probability.",
        type: "info",
      },
      {
        hour: 16,
        message: "Heater ON. Icing probability increasing.",
        type: "info",
      },
      {
        hour: 17,
        message: "High icing probability detected.",
        type: "warning",
      },
      {
        hour: 18,
        message: "High icing probability detected.",
        type: "warning",
      },
      {
        hour: 19,
        message: "Heater remains ON. Severe icing risk.",
        type: "warning",
      },
      {
        hour: 20,
        message: "Heater remains ON. Severe icing risk.",
        type: "warning",
      },
      {
        hour: 21,
        message: "Critical icing probability detected.",
        type: "warning",
      },
      {
        hour: 22,
        message: "Critical icing probability detected.",
        type: "warning",
      },
      {
        hour: 23,
        message: "Critical icing probability detected.",
        type: "warning",
      },
    ],

    first_data_timestamp: "2025-01-25T00:00:00Z",
    last_data_timestamp: "2025-01-25T23:59:59Z",
  },
  {
    id: 3,
    name: "asphalt sensor - Tabriz Urban Main Road",
    uuid: "c8e41b92-9d33-4c8f-b4aa-tabriz003",

    location: {
      address: "Tabriz Main Urban Road, East Azerbaijan, Iran",
      latitude: 38.08,
      longitude: 46.2919,
    },

    status: "online",

    energy: {
      storage: {
        type: "battery",
        capacity_wh: 120000, // 120 kWh
        current_level_percent: 76,
      },
      generation: [
        {
          type: "solar",
          max_power_w: 140,
          efficiency_percent: 18,
        },
        {
          type: "geothermal",
          max_power_w: 60,
        },
      ],
    },

    energy_summary: {
      total_consumed_kwh: 88,
      total_generated_kwh: 16,
      net_consumed_kwh: 72,
    },

    heating_status_daily: [
      { hour: 0, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 1, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 2, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 3, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 4, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 5, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 6, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 7, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 8, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 9, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 10, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 11, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 12, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 13, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 14, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 15, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 16, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 17, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 18, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 19, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 20, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 21, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 22, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
      { hour: 23, status: "ON", source: "geothermal", energy_consumed_kwh: 5 },
    ],

    solar_metrics: {
      source: "pv_atlas",
      period: "daily",
      units: "kWh/m²",
      irradiation: {
        dni: 1420,
        ghi: 1160,
        dhi: 450,
        gti_opt: 1500,
      },
      optimal_panel_position: {
        tilt_deg: 50,
        azimuth_deg: 180,
      },
      environmental_context: {
        avg_air_temperature_c: -1,
        elevation_m: 1350,
      },
    },

    sun_angle_daily: [
      { hour: 0, angle_deg: 0 },
      { hour: 1, angle_deg: 0 },
      { hour: 2, angle_deg: 0 },
      { hour: 3, angle_deg: 0 },
      { hour: 4, angle_deg: 0 },
      { hour: 5, angle_deg: 0 },
      { hour: 6, angle_deg: 2 },
      { hour: 7, angle_deg: 5 },
      { hour: 8, angle_deg: 12 },
      { hour: 9, angle_deg: 20 },
      { hour: 10, angle_deg: 28 },
      { hour: 11, angle_deg: 34 },
      { hour: 12, angle_deg: 37 },
      { hour: 13, angle_deg: 36 },
      { hour: 14, angle_deg: 31 },
      { hour: 15, angle_deg: 23 },
      { hour: 16, angle_deg: 15 },
      { hour: 17, angle_deg: 7 },
      { hour: 18, angle_deg: 0 },
      { hour: 19, angle_deg: 0 },
      { hour: 20, angle_deg: 0 },
      { hour: 21, angle_deg: 0 },
      { hour: 22, angle_deg: 0 },
      { hour: 23, angle_deg: 0 },
    ],

    temperature_records: {
      air_temperature: [
        { hour: 0, value_c: -10.8 },
        { hour: 1, value_c: -11.2 },
        { hour: 2, value_c: -11.6 },
        { hour: 3, value_c: -12.0 },
        { hour: 4, value_c: -12.4 },
        { hour: 5, value_c: -12.0 },
        { hour: 6, value_c: -11.1 },
        { hour: 7, value_c: -9.6 },
        { hour: 8, value_c: -7.8 },
        { hour: 9, value_c: -5.9 },
        { hour: 10, value_c: -3.8 },
        { hour: 11, value_c: -2.2 },
        { hour: 12, value_c: -1.3 },
        { hour: 13, value_c: -1.0 },
        { hour: 14, value_c: -1.6 },
        { hour: 15, value_c: -3.0 },
        { hour: 16, value_c: -4.8 },
        { hour: 17, value_c: -6.5 },
        { hour: 18, value_c: -8.1 },
        { hour: 19, value_c: -9.4 },
        { hour: 20, value_c: -10.1 },
        { hour: 21, value_c: -10.6 },
        { hour: 22, value_c: -11.0 },
        { hour: 23, value_c: -11.4 },
      ],
      asphalt_temperature: [
        { hour: 0, value_c: -8.9 },
        { hour: 1, value_c: -9.4 },
        { hour: 2, value_c: -9.9 },
        { hour: 3, value_c: -10.4 },
        { hour: 4, value_c: -10.8 },
        { hour: 5, value_c: -10.4 },
        { hour: 6, value_c: -9.8 },
        { hour: 7, value_c: -8.6 },
        { hour: 8, value_c: -6.9 },
        { hour: 9, value_c: -4.8 },
        { hour: 10, value_c: -2.9 },
        { hour: 11, value_c: -1.6 },
        { hour: 12, value_c: -0.8 },
        { hour: 13, value_c: -0.6 },
        { hour: 14, value_c: -1.1 },
        { hour: 15, value_c: -2.3 },
        { hour: 16, value_c: -3.9 },
        { hour: 17, value_c: -5.4 },
        { hour: 18, value_c: -7.0 },
        { hour: 19, value_c: -8.3 },
        { hour: 20, value_c: -9.1 },
        { hour: 21, value_c: -9.7 },
        { hour: 22, value_c: -10.2 },
        { hour: 23, value_c: -10.6 },
      ],
    },

    icing_probability_daily: [
      { hour: 0, probability: 0.95 },
      { hour: 1, probability: 0.96 },
      { hour: 2, probability: 0.97 },
      { hour: 3, probability: 0.98 },
      { hour: 4, probability: 0.98 },
      { hour: 5, probability: 0.97 },
      { hour: 6, probability: 0.95 },
      { hour: 7, probability: 0.9 },
      { hour: 8, probability: 0.82 },
      { hour: 9, probability: 0.64 },
      { hour: 10, probability: 0.45 },
      { hour: 11, probability: 0.3 },
      { hour: 12, probability: 0.22 },
      { hour: 13, probability: 0.21 },
      { hour: 14, probability: 0.28 },
      { hour: 15, probability: 0.48 },
      { hour: 16, probability: 0.66 },
      { hour: 17, probability: 0.8 },
      { hour: 18, probability: 0.89 },
      { hour: 19, probability: 0.93 },
      { hour: 20, probability: 0.95 },
      { hour: 21, probability: 0.96 },
      { hour: 22, probability: 0.97 },
      { hour: 23, probability: 0.97 },
    ],

    notifications_daily: [
      {
        hour: 0,
        message: "High icing probability detected (95%). Heater ON.",
        type: "warning",
      },
      {
        hour: 3,
        message: "Sustained freezing conditions detected.",
        type: "warning",
      },
      {
        hour: 7,
        message: "Morning traffic hours. Heater supported by solar.",
        type: "info",
      },
      {
        hour: 8,
        message: "Heater turned OFF. Icing probability dropped.",
        type: "info",
      },
      {
        hour: 12,
        message: "Lowest icing probability recorded today.",
        type: "info",
      },
      {
        hour: 15,
        message: "Heater reactivated due to rising icing probability.",
        type: "info",
      },
      {
        hour: 18,
        message: "High icing probability detected.",
        type: "warning",
      },
      {
        hour: 21,
        message: "Critical icing conditions expected overnight.",
        type: "warning",
      },
    ],

    first_data_timestamp: "2025-01-18T00:00:00Z",
    last_data_timestamp: "2025-01-18T23:59:59Z",
  },
  {
    id: 4,
    name: "asphalt sensor - Hamedan Mountain Road",
    uuid: "f3a92c11-7b21-4f0c-a9dd-hamedan004",

    location: {
      address: "Hamedan - Ganjnameh Mountain Road, Hamedan Province, Iran",
      latitude: 34.7992,
      longitude: 48.5146,
    },

    status: "online",

    energy: {
      storage: {
        type: "battery",
        capacity_wh: 140000, // 140 kWh
        current_level_percent: 69,
      },
      generation: [
        {
          type: "solar",
          max_power_w: 120,
          efficiency_percent: 17,
        },
        {
          type: "geothermal",
          max_power_w: 80,
        },
      ],
    },

    energy_summary: {
      total_consumed_kwh: 95,
      total_generated_kwh: 18,
      net_consumed_kwh: 77,
    },

    heating_status_daily: [
      { hour: 0, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 1, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 2, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 3, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 4, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 5, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 6, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 7, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 8, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 9, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 10, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 11, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 12, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 13, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 14, status: "OFF", source: null, energy_consumed_kwh: 0 },
      { hour: 15, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 16, status: "ON", source: "solar", energy_consumed_kwh: 4 },
      { hour: 17, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 18, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 19, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 20, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 21, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 22, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
      { hour: 23, status: "ON", source: "geothermal", energy_consumed_kwh: 6 },
    ],

    solar_metrics: {
      source: "pv_atlas",
      period: "daily",
      units: "kWh/m²",
      irradiation: {
        dni: 1320,
        ghi: 1040,
        dhi: 420,
        gti_opt: 1420,
      },
      optimal_panel_position: {
        tilt_deg: 55,
        azimuth_deg: 180,
      },
      environmental_context: {
        avg_air_temperature_c: -4,
        elevation_m: 1850,
      },
    },

    sun_angle_daily: [
      { hour: 0, angle_deg: 0 },
      { hour: 1, angle_deg: 0 },
      { hour: 2, angle_deg: 0 },
      { hour: 3, angle_deg: 0 },
      { hour: 4, angle_deg: 0 },
      { hour: 5, angle_deg: 0 },
      { hour: 6, angle_deg: 1 },
      { hour: 7, angle_deg: 4 },
      { hour: 8, angle_deg: 10 },
      { hour: 9, angle_deg: 18 },
      { hour: 10, angle_deg: 26 },
      { hour: 11, angle_deg: 32 },
      { hour: 12, angle_deg: 35 },
      { hour: 13, angle_deg: 34 },
      { hour: 14, angle_deg: 29 },
      { hour: 15, angle_deg: 21 },
      { hour: 16, angle_deg: 13 },
      { hour: 17, angle_deg: 6 },
      { hour: 18, angle_deg: 0 },
      { hour: 19, angle_deg: 0 },
      { hour: 20, angle_deg: 0 },
      { hour: 21, angle_deg: 0 },
      { hour: 22, angle_deg: 0 },
      { hour: 23, angle_deg: 0 },
    ],

    temperature_records: {
      air_temperature: [
        { hour: 0, value_c: -15.2 },
        { hour: 1, value_c: -15.6 },
        { hour: 2, value_c: -16.0 },
        { hour: 3, value_c: -16.4 },
        { hour: 4, value_c: -16.8 },
        { hour: 5, value_c: -16.2 },
        { hour: 6, value_c: -15.1 },
        { hour: 7, value_c: -13.4 },
        { hour: 8, value_c: -11.2 },
        { hour: 9, value_c: -8.9 },
        { hour: 10, value_c: -6.7 },
        { hour: 11, value_c: -5.0 },
        { hour: 12, value_c: -3.9 },
        { hour: 13, value_c: -3.6 },
        { hour: 14, value_c: -4.4 },
        { hour: 15, value_c: -6.0 },
        { hour: 16, value_c: -8.1 },
        { hour: 17, value_c: -10.0 },
        { hour: 18, value_c: -11.9 },
        { hour: 19, value_c: -13.2 },
        { hour: 20, value_c: -14.0 },
        { hour: 21, value_c: -14.6 },
        { hour: 22, value_c: -15.0 },
        { hour: 23, value_c: -15.4 },
      ],
      asphalt_temperature: [
        { hour: 0, value_c: -13.0 },
        { hour: 1, value_c: -13.5 },
        { hour: 2, value_c: -14.0 },
        { hour: 3, value_c: -14.5 },
        { hour: 4, value_c: -14.9 },
        { hour: 5, value_c: -14.3 },
        { hour: 6, value_c: -13.6 },
        { hour: 7, value_c: -12.1 },
        { hour: 8, value_c: -10.2 },
        { hour: 9, value_c: -7.8 },
        { hour: 10, value_c: -5.6 },
        { hour: 11, value_c: -4.1 },
        { hour: 12, value_c: -3.2 },
        { hour: 13, value_c: -3.0 },
        { hour: 14, value_c: -3.6 },
        { hour: 15, value_c: -5.0 },
        { hour: 16, value_c: -6.9 },
        { hour: 17, value_c: -8.6 },
        { hour: 18, value_c: -10.4 },
        { hour: 19, value_c: -11.7 },
        { hour: 20, value_c: -12.5 },
        { hour: 21, value_c: -13.1 },
        { hour: 22, value_c: -13.6 },
        { hour: 23, value_c: -14.0 },
      ],
    },

    icing_probability_daily: [
      { hour: 0, probability: 0.98 },
      { hour: 1, probability: 0.99 },
      { hour: 2, probability: 0.99 },
      { hour: 3, probability: 0.99 },
      { hour: 4, probability: 0.99 },
      { hour: 5, probability: 0.98 },
      { hour: 6, probability: 0.96 },
      { hour: 7, probability: 0.92 },
      { hour: 8, probability: 0.85 },
      { hour: 9, probability: 0.68 },
      { hour: 10, probability: 0.5 },
      { hour: 11, probability: 0.35 },
      { hour: 12, probability: 0.28 },
      { hour: 13, probability: 0.27 },
      { hour: 14, probability: 0.34 },
      { hour: 15, probability: 0.55 },
      { hour: 16, probability: 0.74 },
      { hour: 17, probability: 0.86 },
      { hour: 18, probability: 0.93 },
      { hour: 19, probability: 0.96 },
      { hour: 20, probability: 0.98 },
      { hour: 21, probability: 0.99 },
      { hour: 22, probability: 0.99 },
      { hour: 23, probability: 0.99 },
    ],

    notifications_daily: [
      {
        hour: 0,
        message: "Extreme icing probability detected (98%). Heater ON.",
        type: "warning",
      },
      {
        hour: 4,
        message: "Sustained sub-zero temperatures overnight.",
        type: "warning",
      },
      {
        hour: 7,
        message: "Morning traffic hours. Solar-assisted heating active.",
        type: "info",
      },
      {
        hour: 8,
        message: "Heater turned OFF. Daytime warming observed.",
        type: "info",
      },
      {
        hour: 12,
        message: "Lowest icing probability during midday.",
        type: "info",
      },
      {
        hour: 16,
        message: "Heater reactivated due to rapid temperature drop.",
        type: "info",
      },
      {
        hour: 20,
        message: "Severe icing conditions expected overnight.",
        type: "warning",
      },
    ],

    first_data_timestamp: "2025-01-19T00:00:00Z",
    last_data_timestamp: "2025-01-19T23:59:59Z",
  },
];
